_BASE_: Base-PolypDB_INS-InstanceSegmentation.yaml
MODEL:
  META_ARCHITECTURE: "SiMaskFormer"
  SEM_SEG_HEAD:
    NAME: "SiMaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 2 
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "SiMaskFormerEncoder"
    DIM_FEEDFORWARD: 1024
    NUM_FEATURE_LEVELS: 3
    TOTAL_NUM_FEATURE_LEVELS: 3
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6

  SiMaskFormer:
    TRANSFORMER_DECODER_NAME: "SiMaskFormerDecoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 4.0
    DICE_WEIGHT: 5.0
    MASK_WEIGHT: 5.0
    BOX_WEIGHT: 5.0
    GIOU_WEIGHT: 2.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 9  # 9+1, 9 decoder layers, add one for the loss on learnable query
    DEC_N_POINTS: 8
    TYPE_SAMPLING_LOCATIONS: "mask"
    TYPE_MASK_EMBED: "SumSinusoidalMask"      #['MaskSimpleCNN','SumSinusoidalMask']
    MASK_EMBED_SPATINAL_SHAPE_LEVEL: None    #[None,0,1,2]    None is full-size

    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    INITIAL_PRED: True
    TWO_STAGE: True
    DN: "seg"
    DN_NUM: 50
    DN_NOISE_SCALE: 0.2
    INITIALIZE_BOX_TYPE: "bitmask"
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.25

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  STEPS: (19815,26420)
  MAX_ITER: 29722
  CHECKPOINT_PERIOD: 330
  AMP:
    ENABLED: True
    
TEST:
  DETECTIONS_PER_IMAGE: 100      
  EVAL_PERIOD: 330
  EVAL_START_ITER: 0
#  EVAL_FLAG: 1